sudo: required
services:
  - docker

before_install:
  - docker build -t thabisomofokeng/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true thabisomofokeng/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "af-south-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-af-south-1-252719505540"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
